import 'buffer';
import 'process';
import { Amplify } from 'aws-amplify';
import { signIn, signUp, confirmSignUp, resendSignUpCode, signOut, getCurrentUser } from 'aws-amplify/auth';
import amplifyconfig from './src/amplifyconfiguration.json';

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

Amplify.configure(amplifyconfig);

// Common elements for all pages
const currentPath = window.location.pathname;
const appBasePath = '/Good-Loop_iyilik-zinciri_/'; // Base path for GitHub Pages deployment

// Function to check if user is authenticated and redirect
async function checkAuthAndRedirect() {
    try {
        await getCurrentUser();
        // User is authenticated, redirect to home.html if not already there
        if (!currentPath.includes('home.html')) {
            window.location.href = './home.html';
        }
    } catch (error) {
        // User is not authenticated.
        // If they are on the login page (index.html or base path), do nothing.
        // Otherwise, redirect them to the login page.
        const isLoginPage = (currentPath === appBasePath || currentPath === `${appBasePath}index.html`);
        if (!isLoginPage && !currentPath.includes('verify.html')) {
            window.location.href = './index.html';
        }
    }
}

// Execute checkAuthAndRedirect on page load for all pages except verify.html
if (!currentPath.includes('verify.html')) {
    checkAuthAndRedirect();
}

// Logic for index.html (Login/Signup Page)
if (currentPath === appBasePath || currentPath === `${appBasePath}index.html`) {
    const container = document.getElementById('auth-container-animated');
    const registerBtn = document.getElementById('register');
    const loginBtn = document.getElementById('login');
    const showLoginMobileBtn = document.getElementById('show-login-mobile');
    const showSignupMobileBtn = document.getElementById('show-signup-mobile');

    const signupPasswordInput = document.getElementById('signup-password');
    const strengthBar = document.querySelector('.strength-bar');
    const strengthText = document.getElementById('strength-text');
    const signupButton = document.getElementById('signup-button');

    const toggleForm = (isRegister) => {
        if (container) {
            if (isRegister) {
                container.classList.add('active');
            } else {
                container.classList.remove('active');
            }
        }
    };

    // Ensure event listeners are attached only if elements exist
    if (registerBtn) {
        registerBtn.addEventListener('click', () => toggleForm(true));
    }

    if (loginBtn) {
        loginBtn.addEventListener('click', () => toggleForm(false));
    }

    if (showLoginMobileBtn) {
        showLoginMobileBtn.addEventListener('click', (e) => {
            e.preventDefault();
            toggleForm(false);
        });
    }

    if (showSignupMobileBtn) {
        showSignupMobileBtn.addEventListener('click', (e) => {
            e.preventDefault();
            toggleForm(true);
        });
    }

    // Password Strength Logic
    if (signupPasswordInput) {
        signupPasswordInput.addEventListener('input', () => {
            const password = signupPasswordInput.value;
            const requirements = [
                { regex: /.{8,}/, message: "En az 8 karakter" },
                { regex: /[A-Z]/, message: "Büyük harf (A-Z)" },
                { regex: /[a-z]/, message: "Küçük harf (a-z)" },
                { regex: /[0-9]/, message: "Sayı (0-9)" },
                { regex: /[!@#$%^&*]/, message: "Özel karakter (!@#$%^&*)" }
            ];

            let strength = 0;
            let firstUnmetRequirement = null;

            requirements.forEach(req => {
                if (req.regex.test(password)) {
                    strength++;
                } else if (!firstUnmetRequirement) {
                    firstUnmetRequirement = req.message;
                }
            });

            const strengthPercentage = (strength / requirements.length) * 100;
            strengthBar.style.width = `${strengthPercentage}%`;

            if (strength === requirements.length) {
                strengthText.textContent = "Güçlü Şifre";
                signupButton.style.display = 'block';
            } else {
                strengthText.textContent = `${strength}/${requirements.length}: ${firstUnmetRequirement}`;
                signupButton.style.display = 'none';
            }

            strengthBar.classList.remove('weak', 'medium', 'strong');
            if (strengthPercentage < 40) {
                strengthBar.classList.add('weak');
            } else if (strengthPercentage < 80) {
                strengthBar.classList.add('medium');
            } else {
                strengthBar.classList.add('strong');
            }
        });
    }

    // Form submission logic (Amplify)
    const loginForm = document.getElementById('login-form');
    const signupForm = document.getElementById('signup-form');

    if (loginForm) {
        loginForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const email = document.getElementById('login-email').value;
            const password = document.getElementById('login-password').value;
            try {
                await signIn({ username: email, password });
                alert('Giriş başarılı!');
                window.location.href = './home.html';
            } catch (error) {
                console.error('Giriş hatası:', error);
                if (error.name === 'UserNotConfirmedException') {
                    alert('Hesabınız doğrulanmamış. Lütfen e-postanızı doğrulayın.');
                    // Redirect to verification page with email
                    window.location.href = `./verify.html?email=${encodeURIComponent(email)}`;
                } else {
                    alert(error.message);
                }
            }
        });
    }

    if (signupForm) {
        signupForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const email = document.getElementById('signup-email').value;
            const password = document.getElementById('signup-password').value;
            try {
                await signUp({ username: email, password, attributes: { email } });
                alert('Kayıt başarılı! Lütfen e-postanıza gönderilen doğrulama linkine tıklayın.');
                // Redirect to verification page with email
                window.location.href = `./verify.html?email=${encodeURIComponent(email)}`;
            } catch (error) {
                console.error('Kayıt hatası:', error);
                alert(error.message);
            }
        });
    }
}

// Logic for verify.html (Email Verification Page)
if (currentPath.includes('verify.html')) {
    const verifyForm = document.getElementById('verify-form');
    const verifyEmailInput = document.getElementById('verify-email');
    const verificationCodeInput = document.getElementById('verification-code');
    const resendCodeButton = document.getElementById('resend-code-button');

    // Pre-fill email if available from URL
    const urlParams = new URLSearchParams(window.location.search);
    const emailFromUrl = urlParams.get('email');
    if (emailFromUrl) {
        verifyEmailInput.value = emailFromUrl;
    }

    if (verifyForm) {
        verifyForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const email = verifyEmailInput.value;
            const code = verificationCodeInput.value;
            try {
                await confirmSignUp({ username: email, confirmationCode: code });
                alert('E-posta başarıyla doğrulandı! Şimdi giriş yapılıyor...');
                // After successful confirmation, try to sign in automatically
                // If confirmSignUp doesn't automatically sign in, user will be redirected to login page
                // Removed automatic sign-in here to avoid password prompt
                window.location.href = './home.html'; // Redirect directly to home after successful verification
            } catch (error) {
                console.error('Doğrulama hatası:', error);
                alert(error.message);
                // If confirmation fails, stay on verification page or redirect to login if needed
                // For now, stay on verification page to allow re-entry or resend
            }
        });
    }

    if (resendCodeButton) {
        resendCodeButton.addEventListener('click', async () => {
            const email = verifyEmailInput.value;
            if (!email) {
                alert('Lütfen e-posta adresinizi girin.');
                return;
            }
            try {
                await resendSignUpCode({ username: email });
                alert('Doğrulama kodu tekrar gönderildi.');
            } catch (error) {
                console.error('Kodu tekrar gönderme hatası:', error);
                alert(error.message);
            }
        });
    }
}

// Logic for home.html (Home Page)
if (currentPath.includes('home.html')) {
    const logoutButton = document.getElementById('logout-button');

    if (logoutButton) {
        logoutButton.addEventListener('click', async () => {
            try {
                await signOut();
                alert('Başarıyla çıkış yapıldı.');
                window.location.href = './index.html';
            } catch (error) {
                console.error('Çıkış yapma hatası:', error);
                alert(error.message);
            }
        });
    }
}