import 'buffer';
import 'process';
import Amplify from 'aws-amplify';

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:b7605fa3-c401-4071-84b4-eb4383cb316e",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_kQfNhi2r1",
    "aws_user_pools_web_client_id": "157pb1sto8hhegfjfqsnbf2vk3",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

    Amplify.configure(awsmobile);

    const container = document.getElementById('auth-container-animated');
    const registerBtn = document.getElementById('register');
    const loginBtn = document.getElementById('login');
    const showLoginMobileBtn = document.getElementById('show-login-mobile');
    const showSignupMobileBtn = document.getElementById('show-signup-mobile');

    const toggleForm = (isRegister) => {
        if (container) {
            if (isRegister) {
                container.classList.add('active');
            } else {
                container.classList.remove('active');
            }
        }
    };

    if (registerBtn) {
        registerBtn.addEventListener('click', () => toggleForm(true));
    }

    if (loginBtn) {
        loginBtn.addEventListener('click', () => toggleForm(false));
    }

    if (showLoginMobileBtn) {
        showLoginMobileBtn.addEventListener('click', (e) => {
            e.preventDefault();
            toggleForm(false);
        });
    }

    if (showSignupMobileBtn) {
        showSignupMobileBtn.addEventListener('click', (e) => {
            e.preventDefault();
            toggleForm(true);
        });
    }

    // Form gönderme işlemleri (Amplify ile)
    const loginForm = document.getElementById('login-form');
    const signupForm = document.getElementById('signup-form');

    if (loginForm) {
        loginForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const email = document.getElementById('login-email').value;
            const password = document.getElementById('login-password').value;
            try {
                await Amplify.Auth.signIn(email, password);
                alert('Giriş başarılı!');
                // window.location.href = '/dashboard'; 
            } catch (error) {
                console.error('Giriş hatası:', error);
                alert(error.message);
            }
        });
    }

    if (signupForm) {
        signupForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const email = document.getElementById('signup-email').value;
            const password = document.getElementById('signup-password').value;
            try {
                await Amplify.Auth.signUp({ username: email, password, attributes: { email } });
                alert('Kayıt başarılı! Lütfen e-postanıza gönderilen doğrulama linkine tıklayın.');
                toggleForm(false); // Kayıttan sonra giriş formunu göster
            } catch (error) {
                console.error('Kayıt hatası:', error);
                alert(error.message);
            }
        });
    }
